version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - 1433:1433
    secrets:
      - db_password

  # storage:
  #   image: mcr.microsoft.com/azure-storage/azurite
  #   ports:
  #     - 10000:10000
  #     - 10001:10001
  #     - 10002:10002
  #   volumes:
  #     - /data:./_data

  server:
    image: server
    build:
      context: .
      dockerfile: ./MyApp.Server/Dockerfile
    ports:
      - 5077:5077
      - 7207:7207
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - db
    secrets:
      - source: connection_string
        target: ConnectionStrings__Comics

secrets:
  db_password:
    file: ./.local/db_password.txt
  connection_string:
    file: ./.local/connection_string.txt
