version: '3.9'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD:

  web:
    image: web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    environment:
      ConnectionStrings__Comics:
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - db
