version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - 1433:1433
    secrets:
      - db_password

  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - './.local/temp:/data/'

  server:
    image: server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ConnectionStrings__Comics:
      BlobContainerUri: https://storage:10000/devstoreaccount1/images
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: localhost
    ports:
      - 5077:80
      - 7207:443
    depends_on:
      - db
      - storage
    secrets:
      - source: connection_string
        target: ConnectionStrings__Comics
    volumes:
      - '../../../../.aspnet/https:/https/'
      - ~/.vsdbg:/remote_debugger:rw

secrets:
  db_password:
    file: ./.local/db_password.txt
  connection_string:
    file: ./.local/connection_string.txt
